prose:
  rooturl: '_posts'
  siteurl: 'http://muenster-roadrunners.github.io/ms-roadrunners.de/'
  media: 'media'
  metadata:
    _posts:


team:
	- name: Mila Frerichs
      position: OF
    - name: Björn Helfer
      position: SS, 3B, OF